### ISSUE TITLE
error on `ember install`

### ISSUE THREAD

**Issue by mszoernyi** [xcambar/ember-cli-self-update#1]
`$ ember install ember-cli-self-update`

> The package `ember-cli-self-update` is not a properly formatted package, we have used a fallback lookup to resolve it at `/project/node_modules/ember-cli-self-update`. This is generally caused by an addon not having a `main` entry point (or `index.js`).
> The `ember-cli-self-update` addon could not be found at `/project/node_modules/ember-cli-self-update`.

**Comment by xcambar** [comment]
Thanks for the report.
I have pushed a new version (`0.1.2`) that supposedly fixes it.

Tell me how it goes for you so I can close it.

**Comment by mszoernyi** [comment]
This was quick, it works.

Thanks!
